version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "terraform"
    directory: "/deployment"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/git-simple-http"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/nginx"
    schedule:
      interval: "weekly"
