// Generated by CoffeeScript 1.10.0
var chai, expect, randomiser;

chai = require("chai");

randomiser = require("../../swapper/listRandomiser");

expect = chai.expect;

describe('listRandomiser', function() {
  return describe('#randomise()', function() {
    return it('swaps elements in an array with count 2', function() {
      return expect(randomiser.randomise([1, 2])).to.deep.equal([2, 1]);
    });
  });
});
