// Generated by CoffeeScript 1.10.0
var checker, connection, correct, generateQandA, io, requiredAttempts, round, setResult;

connection = require('./connection');

round = require('./round');

checker = require('../challenges/checker');

io = null;

exports.initIo = function(_io) {
  return io = _io;
};

exports.question = function(req, res) {
  var challengeCollection, context;
  context = {};
  challengeCollection = connection.collection('challenge');
  return round.getRound().then(function(round) {
    var challenge;
    context.round = round;
    challenge = generateQandA(round);
    challenge.team = req.params['team'];
    context.challenge = challenge;
    return challengeCollection.findOne({
      team: challenge.team
    });
  }).then(function(oldChallenge) {
    if (oldChallenge) {
      context.challenge._id = oldChallenge._id;
      if (oldChallenge.result && oldChallenge.count < requiredAttempts(context.round) && oldChallenge.round === context.round) {
        context.challenge.count = oldChallenge.count + 1;
      }
    }
    return challengeCollection.save(context.challenge, {
      safe: true
    });
  }).then(function() {
    if (context.challenge.count === 0) {
      io.emit('result', {
        team: context.challenge.team,
        round: context.round,
        status: 'working'
      });
    }
    return res.json(context.challenge.question);
  })["catch"](function(error) {
    console.log(error);
    return res.status(500).json(error);
  });
};

exports.answer = function(req, res) {
  var challengeCollection, context, team;
  team = req.params['team'];
  challengeCollection = connection.collection('challenge');
  context = {};
  return round.getRound().then(function(round) {
    context.round = round;
    return challengeCollection.findOne({
      team: team
    });
  }).then(function(doc) {
    doc.result = correct(req.body, doc.answer, context.round);
    context.doc = doc;
    return challengeCollection.save(doc, {
      safe: true
    });
  }).then(function() {
    return setResult(context.round, team, context.doc.result, context.doc.count);
  }).then(function(status) {
    if (status !== 'working') {
      io.emit('result', {
        team: team,
        round: context.round,
        status: status
      });
    }
    if (context.doc.result) {
      if (context.doc.count >= requiredAttempts(context.round)) {
        return res.status(200).send("OK");
      } else {
        return res.redirect(303, "/routes/challenge/" + team);
      }
    } else {
      return res.status(418).json({
        yourAnswer: req.body,
        correctAnswer: context.doc.answer
      });
    }
  })["catch"](function(error) {
    console.log(error);
    return res.status(500).json(error);
  });
};

setResult = function(round, team, gotItRight, count) {
  var branchesCollection, status;
  branchesCollection = connection.collection('branches');
  status = null;
  return branchesCollection.findOne({
    name: team
  }).then(function(doc) {
    if (!gotItRight) {
      status = 'failure';
    } else if (count === requiredAttempts(round)) {
      status = 'success';
    } else {
      status = 'working';
    }
    doc[round] = status;
    return branchesCollection.save(doc, {
      safe: true
    });
  }).then(function() {
    return status;
  });
};

requiredAttempts = function(round) {
  if (round === 0) {
    return 2;
  }
  return round * 5;
};

correct = function(reqBody, answer, round) {
  return checker.check(answer, reqBody);
};

generateQandA = function(round) {
  var challenge;
  challenge = require("../challenges/challenge" + round).challenge();
  challenge.round = round;
  challenge.count = 0;
  challenge.result = false;
  return challenge;
};
