// Generated by CoffeeScript 1.10.0
var client, collections, mongoClient;

mongoClient = require('mongodb').MongoClient;

client = null;

collections = {};

exports.init = function() {
  return mongoClient.connect('mongodb://127.0.0.1:27017/CodeWhispers').then(function(db) {
    return client = db;
  });
};

exports.collection = function(collectionName) {
  if (!collections[collectionName]) {
    collections[collectionName] = client.collection(collectionName);
  }
  return collections[collectionName];
};
