// Generated by CoffeeScript 1.10.0
var round;

round = require('./round');

exports.dashboard = function(req, res) {
  return res.render('dashboard', {
    title: 'CodeWhispers'
  });
};

exports.controlPanel = function(req, res) {
  return res.render('controlPanel', {
    title: 'CodeWhispers'
  });
};

exports.whisper = function(req, res) {
  return round.getRound().then(function(roundNumber) {
    return res.render("q" + roundNumber, function(err, q) {
      return res.render('instructions', {
        title: 'CodeWhispers',
        q: q
      });
    });
  })["catch"](function(error) {
    return res.status(500).send(error);
  });
};

exports.question = function(req, res) {
  var roundNumber;
  roundNumber = req.params['round'];
  return res.render("q" + roundNumber);
};
