// Generated by CoffeeScript 1.10.0
var connection, getRound, io, setRound;

connection = require('./connection');

io = null;

exports.initIo = function(_io) {
  io = _io;
  return io.on('connection', function(socket) {
    return getRound().then(function(round) {
      return socket.emit('new round', round);
    })["catch"](function(error) {
      return console.log(error);
    });
  });
};

exports.set = function(req, res) {
  var number;
  number = req.body.number;
  return setRound(number).then(function() {
    return res.status(200).send("Round: " + number);
  })["catch"](function(error) {
    return res.status(500).send(error);
  });
};

exports.increment = function() {
  return getRound().then(function(round) {
    round += 1;
    return setRound(round);
  });
};

setRound = function(number) {
  var challenges, round;
  challenges = connection.collection('challenge');
  round = connection.collection('round');
  return challenges.remove({}, {
    safe: true
  }).then(function() {
    return round.remove({}, {
      safe: true
    });
  }).then(function() {
    return round.save({
      round: number
    }, {
      safe: true
    });
  }).then(function() {
    io.emit('new round', number);
    return number;
  });
};

getRound = function() {
  var roundCollection;
  roundCollection = connection.collection('round');
  return roundCollection.findOne({}).then(function(doc) {
    return doc.round;
  });
};

exports.getRound = getRound;
