// Generated by CoffeeScript 1.10.0
var random, randomise;

randomise = function(list) {
  var i, j, k, ref, ref1;
  list = list.slice(0);
  for (i = k = 0, ref = list.length - 1; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
    j = random(i + 1, list.length);
    ref1 = [list[j], list[i]], list[i] = ref1[0], list[j] = ref1[1];
  }
  return list;
};

random = function(min, max) {
  return min + Math.floor(Math.random() * (max - min));
};

exports.randomise = randomise;
