// Generated by CoffeeScript 1.10.0
var _, chai, expect, subject;

chai = require("chai");

subject = require("../../challenges/challenge1");

_ = require("underscore");

expect = chai.expect;

describe('challenge1', function() {
  it('returns a string of F for instructions', function() {
    var challenge;
    challenge = subject.challenge();
    expect(challenge.question.instructions.length).to.be.above(0);
    return _.each(challenge.question.instructions, function(char) {
      return expect(char).to.equal('F');
    });
  });
  return it('end differs from start by length of instructions', function() {
    var a, challenge, q;
    challenge = subject.challenge();
    q = challenge.question;
    a = challenge.answer;
    return expect(q.start + q.instructions.length).to.equal(a.end);
  });
});
