// Generated by CoffeeScript 1.10.0
var chai, expect, subject;

chai = require("chai");

subject = require("../../challenges/challenge0");

expect = chai.expect;

describe('challenge0', function() {
  return it('returns same start and end number', function() {
    var challenge;
    challenge = subject.challenge();
    return expect(challenge.question.start).to.equal(challenge.answer.end);
  });
});
