// Generated by CoffeeScript 1.10.0
var challengeUtils, getChallenge;

challengeUtils = require('./challengeUtils');

exports.challenge = function() {
  var shouldFindTreasure;
  shouldFindTreasure = Math.floor(Math.random() * 2) === 1;
  return getChallenge(shouldFindTreasure);
};

getChallenge = function(shouldFindTreasure) {
  var endPosition, instructions, startX, startY, treasureCoordinate;
  startX = Math.floor(Math.random() * 20) + 10;
  startY = Math.floor(Math.random() * 20) + 10;
  instructions = challengeUtils.getInstructions(Math.floor(Math.random() * 10) + 10);
  endPosition = challengeUtils.calculateEndPosition(instructions, [startX, startY]);
  treasureCoordinate = challengeUtils.calculateItemCoordinate(instructions, shouldFindTreasure, [startX, startY]);
  return {
    question: {
      startX: startX,
      startY: startY,
      treasureX: treasureCoordinate[0],
      treasureY: treasureCoordinate[1],
      instructions: instructions.join('')
    },
    answer: {
      endX: endPosition[0],
      endY: endPosition[1],
      treasureFound: shouldFindTreasure
    }
  };
};

exports.getChallenge = getChallenge;
