// Generated by CoffeeScript 1.10.0
exports.challenge = function() {
  var distance, start;
  start = Math.floor(Math.random() * 10);
  distance = Math.floor(Math.random() * 10) + 1;
  return {
    question: {
      start: start,
      instructions: Array(distance + 1).join('F')
    },
    answer: {
      end: start + distance
    }
  };
};
