// Generated by CoffeeScript 1.10.0
exports.check = function(answer, response) {
  var item, matches;
  matches = [];
  for (item in answer) {
    matches.push(answer[item] === response[item]);
  }
  return matches.reduce(function(a, b) {
    return a && b;
  });
};
